[package]
name = "mookaite"
version = "0.5.0"
authors = ["buddja <buddjad@gmail.com>"]
readme = "README.md"

[dependencies]
rand = "0.3.15"
walkdir = "1.0.3"
clap = "2.19.2"
mio = "*"
xlib = { git = "https://github.com/bytebuddha/xlib.git" }
